name: fruits_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: 