name: fruits_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  dartz: ^0.10.1
  firebase_auth: ^6.0.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  modal_progress_hud_nsn: ^0.5.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
 


dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
flutter_intl:
  enabled: true