// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTfWcyTTCotSef1LV2pKG4QxgAUXFCWU',
    appId: '1:669279025672:web:ec3e3236e6332e63dc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    authDomain: 'fruit-hub-ae74c.firebaseapp.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    measurementId: 'G-HSEGT1794Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcpZDHXSBb-DTUajK0i2DrW_V8d1mpAMM',
    appId: '1:669279025672:android:89af1785f9bc3dd9dc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQiUA303Vj06Nn3qZFfDNRhI0BmBkQctY',
    appId: '1:669279025672:ios:694b1cd06fbe3693dc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQiUA303Vj06Nn3qZFfDNRhI0BmBkQctY',
    appId: '1:669279025672:ios:694b1cd06fbe3693dc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaTfWcyTTCotSef1LV2pKG4QxgAUXFCWU',
    appId: '1:669279025672:web:1b29474ef075925bdc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    authDomain: 'fruit-hub-ae74c.firebaseapp.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    measurementId: 'G-2606QHC8Z2',
  );
}
