// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxKw6Ob7v7dXrW-lYXYQpFJFDico0-9YU',
    appId: '1:266551094903:web:b40f4af09fefb80bea2072',
    messagingSenderId: '266551094903',
    projectId: 'fruitshub-fef24',
    authDomain: 'fruitshub-fef24.firebaseapp.com',
    storageBucket: 'fruitshub-fef24.firebasestorage.app',
    measurementId: 'G-R0HVHE0066',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQWmlVgAMXcoXFGP4UGyHROuU-WOv39Q',
    appId: '1:266551094903:android:5f9b1c6d595dbd2bea2072',
    messagingSenderId: '266551094903',
    projectId: 'fruitshub-fef24',
    storageBucket: 'fruitshub-fef24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8JAuT_a55VgCiL1RCgNzY9fmKjQAaas',
    appId: '1:266551094903:ios:83607baed4935e48ea2072',
    messagingSenderId: '266551094903',
    projectId: 'fruitshub-fef24',
    storageBucket: 'fruitshub-fef24.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY8JAuT_a55VgCiL1RCgNzY9fmKjQAaas',
    appId: '1:266551094903:ios:83607baed4935e48ea2072',
    messagingSenderId: '266551094903',
    projectId: 'fruitshub-fef24',
    storageBucket: 'fruitshub-fef24.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxKw6Ob7v7dXrW-lYXYQpFJFDico0-9YU',
    appId: '1:266551094903:web:5235bd662067089aea2072',
    messagingSenderId: '266551094903',
    projectId: 'fruitshub-fef24',
    authDomain: 'fruitshub-fef24.firebaseapp.com',
    storageBucket: 'fruitshub-fef24.firebasestorage.app',
    measurementId: 'G-Z2GX34KCVH',
  );
}
